plugin:
  name: custom-data-type-georef
  version: 1.2
  url: https://github.com/programmfabrik/easydb-custom-data-type-georef
  displayname:
    de-DE: georef-Verknüpfung
    en-US: georef-Referencing
  info:
    de-DE: Ermöglicht Georeferenzierungen auf einer Karte im geoJSON-Format.
    en-US: Enables georeferencing on a map in geoJSON format.
  server:
    api-version:
      require: 1
  scss:
    body:
      - build/webfrontend/custom-data-type-georef.scss
  webfrontend:
    url: custom-data-type-georef.js
    l10n: l10n/
    css: mapbox.css
custom_types:
  georef:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
    config:
      schema:
        - name: mapbox_access_token
          parameters:
            value:
              type: text
